version: '2'

services:

  vote:
    build: .
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
