version: '2'

services:

  vote:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - front-tier
      - back-tier
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
